# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v2
      with:
        version: '1'
    - run: mkdir ./strava_data || echo "Directory already exists" # Create the directory for storing Strava data
    - run: touch ./strava_data/user.json
    # - name: Download previous data.jld2 artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: data-jld2
    #     path: strava_data # Download the artifact to the specified directory
    #     if-no-files-found: ignore # Ignore if no files are found, to prevent the workflow from failing
    - run: julia .github/workflows/download_all.jl
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_DATA_DIR: ./strava_data
        USER_JSON: ${{ secrets.USER_JSON }} # Pass the user JSON as an environment variable
    - name: Upload data.jld2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-jld2
        path: $STRAVA_DATA_DIR/data.jld2
